<script>
require([
	'jquery'
], function($) {$(function() {
    // Your custom code here...

    var ratingApp_carouselScript = document.createElement("script");  // create a script DOM node
    ratingApp_carouselScript.src = 'https://reviews-ai.ngrok.io/JavaScript/carousel.js';  // set its src to the provided URL
    ratingApp_carouselScript.dataset.wid = '<?php echo $block->getWebsiteID() ?>';
    ratingApp_carouselScript.id='ratingAppCarouselScript';
    document.head.appendChild(ratingApp_carouselScript);  // add it to the end of the head section of the page (could change 'head' to 'body' to add it to the end of the body section instead)
  

});});
