<script>
require([
	'jquery'
], function($) {$(function() {
    // Your custom code here...

    var ratingApp_script = document.createElement("script");  // create a script DOM node
    ratingApp_script.src = 'https://reviews-ai.ngrok.io/JavaScript/widget.js';  // set its src to the provided URL
    ratingApp_script.dataset.wid = '<?php echo $block->getWebsiteID() ?>';
    ratingApp_script.id='ratingAppWidgetScript';
    document.head.appendChild(ratingApp_script);  // add it to the end of the head section of the page (could change 'head' to 'body' to add it to the end of the body section instead)
    
});});
</script>
